### ISSUE TITLE
【建议】bangumi游戏分类文本修改

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#1]
![Clip_2024-02-10_12-06-52](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/a0431be4-a82d-4992-bf6d-0c08ef36b876)
如图，游戏分类的文本应该是`想玩`、`在玩`和`玩过`，而不是和番剧用的文本一样

**Comment by yixiaojiu** [comment]
感谢指出，没注意到

**Comment by yixiaojiu** [comment]
已经改了
