### ISSUE TITLE
【Bug】vercel部署后访问失败

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#2]
![Clip_2024-02-19_11-39-11](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/ebb95dd3-44ff-43b8-9f3a-27e11b8f2591)
![Clip_2024-02-19_11-40-05](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/3f627bb5-02f9-46e2-9823-19e9f1765fb7)

**Comment by yixiaojiu** [comment]
请求地址为什么是 http://localhost:3000/api ？

**Comment by yixiaojiu** [comment]
<img width="1592" alt="image" src="https://github.com/yixiaojiu/bilibili-bangumi-component/assets/63455218/60f4e9eb-6323-4166-b071-2a9bf2786730">

<img width="1047" alt="image" src="https://github.com/yixiaojiu/bilibili-bangumi-component/assets/63455218/a446fa7a-4af7-4d53-afe6-31755ee91987">

你可以查一下 vercel 的构建记录，看看是否有 functions

**Comment by yixiaojiu** [comment]
如果你是本地调试的话，可以运行 `vercel dev`，然后就可以通过 http://localhost:3000/api 调用接口了

**Comment by MengNianxiaoyao** [comment]
> <img alt="image" width="1592" src="https://private-user-images.githubusercontent.com/63455218/305783416-60f4e9eb-6323-4166-b071-2a9bf2786730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYyMjAsIm5iZiI6MTcwODMxNTkyMCwicGF0aCI6Ii82MzQ1NTIxOC8zMDU3ODM0MTYtNjBmNGU5ZWItNjMyMy00MTY2LWIwNzEtMmE5YmYyNzg2NzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODMwZjBlNzRlMzBiZGYyMGE0MDY4NzZhNTg2NTE2ZWY2M2U1YmRjOTJkYWM1YTNkZTczOTBjNzcwYWM5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lau3M0b1Xx1zfBkAvUDTMdgdcxPJ5XuZ69aHgtDJnf4"> <img alt="image" width="1047" src="https://private-user-images.githubusercontent.com/63455218/305783500-a446fa7a-4af7-4d53-afe6-31755ee91987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYyMjAsIm5iZiI6MTcwODMxNTkyMCwicGF0aCI6Ii82MzQ1NTIxOC8zMDU3ODM1MDAtYTQ0NmZhN2EtNGFmNy00ZDUzLWFmZTYtMzE3NTVlZTkxOTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MjI5NTE4ZWZiM2Y2YmFhN2QwMzA3MTQ3MWY1NTlhNmIyMTMyOTQ2YTMyY2I5MjVhZWFmM2Y1YThhNDBkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wt-ryaQFxreYZsXUfDbwylVVKpFsf2LtV4uspIgt5rg">
> 你可以查一下 vercel 的构建记录，看看是否有 functions

没有

**Comment by MengNianxiaoyao** [comment]
搞定了，真是难蚌。
根目录得root，framework要other，vercel默认的直接不行

**Comment by yixiaojiu** [comment]
我看看能不能在vercel.json里默认配置好

**Comment by MengNianxiaoyao** [comment]
文档里得给个vercel部署成功的例图，部署成功我记得是打印出了`hhh`

**Comment by yixiaojiu** [comment]
等会完善一下。没用过cf，对cf不熟😭

**Comment by MengNianxiaoyao** [comment]
> 等会完善一下。没用过cf，对cf不熟😭

cf的worker就是serverless function，和val towm差不多

**Comment by yixiaojiu** [comment]
> 文档里得给个vercel的部署步骤和部署成功的例图，部署成功我记得是打印出了`hhh` cf的worker也可以写一个，我测试就是没有`Access-Control-Allow-Origin`这个响应标头的报错

增加了对 cloudflare worker 的支持 https://github.com/yixiaojiu/bilibili-bangumi-component/blob/main/api/cloudflare.js

![image](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/63455218/86e13229-d6fa-4cc6-9ad3-2cafabe6d2b1)
环境变量在这添加
