### ISSUE TITLE
【Bug】bangumi里的游戏分类`想玩`和`在玩`内容反了

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#3]
![Clip_2024-02-20_07-40-53](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/3884a70f-6daf-4a77-8f81-95152c36b5bb)

![Clip_2024-02-20_07-40-45](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/6bbd75b9-bef7-4b41-b107-1cdb446e89c3)

**Comment by yixiaojiu** [comment]
<img width="369" alt="image" src="https://github.com/yixiaojiu/bilibili-bangumi-component/assets/63455218/2ad36c97-7dff-430c-8b8b-9f35f68b4b70">

我的想法是和动画板块对其

**Comment by yixiaojiu** [comment]
好的
