### ISSUE TITLE
【Bug】bangumi状态栏显示错误

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#4]
![Clip_2024-02-20_07-46-05](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/2e9538f4-8819-4991-a35d-685758beff05)
如图，如果bangumi内容以及是`游戏`分类，切到bilibili在切回bangumi，是`动画`分类但状态栏是`游戏`分类的

**Comment by MengNianxiaoyao** [comment]
![Clip_2024-02-20_07-49-26](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/e9b4a566-4119-4dd5-8e56-d3748b350cd4)
如图，如果bangumi内容以及是游戏分类，切到bilibili也显示`游戏`分类状态栏

**Comment by yixiaojiu** [comment]
感谢指出，自己用的时候没测这么细

**Comment by yixiaojiu** [comment]
看来要写测试用例了

**Comment by yixiaojiu** [comment]
@MengNianxiaoyao 感谢你所指出的问题，目前已经修复了，更新组件的时候记得把后端也更新一下。
