### ISSUE TITLE
【建议】能否将鼠标样式抽出来进行自定义？

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#5]
在valaxy不好替换鼠标样式

**Comment by yixiaojiu** [comment]
怎么抽离呢，每个元素的 `cursor` 都设置一个 CSS 变量吗？

**Comment by yixiaojiu** [comment]
要不要考虑在 valaxy addon 中暴露 api，方便覆盖样式

**Comment by yixiaojiu** [comment]
<img width="590" alt="image" src="https://github.com/yixiaojiu/bilibili-bangumi-component/assets/63455218/6f82f4fe-0fe6-4bce-9795-2d887c9ce892">

这样可以吗？

**Comment by MengNianxiaoyao** [comment]
> 要不要考虑在 valaxy addon 中暴露 api，方便覆盖样式

暴露api吧，想自定义的就可以自定义，不需要在原先的样式里面添加需要自定义的元素
