### ISSUE TITLE
【Bug】需要正则去除特殊字符转义

### ISSUE THREAD

**Issue by MengNianxiaoyao** [yixiaojiu/bilibili-bangumi-component#6]
![Clip_2024-02-21_19-41-09](https://github.com/yixiaojiu/bilibili-bangumi-component/assets/103258286/5538cba7-2fb2-4ed8-8374-890a95da20b5)
如图，转义连同特殊字符都显示了，应该只保留特殊字符

**Comment by yixiaojiu** [comment]
啊！能提供一下这个动画的 Bangumi 链接吗？

**Comment by yixiaojiu** [comment]
已经修复，并且 valaxy addon 也更新了
