### ISSUE TITLE
【Bug】0.2.1版本的 valaxy-addon-bangumi 插件无法自定义 CSS 样式

### ISSUE THREAD

**Issue by mewhz** [yixiaojiu/bilibili-bangumi-component#9]
当前 valaxy-addon-bangumi 使用0.2.1
![image](https://github.com/user-attachments/assets/d421ff06-836d-451e-b966-bd06657eb08c)
设置 CSS 样式
![image](https://github.com/user-attachments/assets/19c1f0e6-26ad-48fb-a91a-6e7379a2a89e)
标题样式无变化
![image](https://github.com/user-attachments/assets/01611eb0-c9d0-496c-9593-285c6f697569)
但是若修改页面的 index.md 文件，样式则会生效，但是刷新一次后依然失效
![image](https://github.com/user-attachments/assets/7f4c8b75-ea35-46c9-8ca5-66bcd4bd66e3)
![image](https://github.com/user-attachments/assets/7a42ec25-ca9c-4be3-85dc-8d2045bc26a2)
回退 valaxy-addon-bangumi 版本为 0.2.0
pnpm install valaxy-addon-bangumi@0.2.0
![image](https://github.com/user-attachments/assets/b7bf09c8-092c-4b4f-baa5-c93c12cd1db2)
由于该版本无法使用 dev 本地查看
使用 pnpm run build 命令生成 dist 文件夹
通过 VS Code 的 Live Server 插件打开 dist 文件夹，修改的样式生效
![image](https://github.com/user-attachments/assets/fdd2e1c8-e030-4a63-ac13-7864d3749b29)
通过该办法测试新版本的插件
pnpm install valaxy-addon-bangumi@0.2.1
pnpm run build
修改的样式依然无效
![image](https://github.com/user-attachments/assets/c49de8f6-10a8-48b1-b9ac-ba2b5d9bdb5a)

另外使用 chrome 浏览器访问时，若下方的 value 过长则会出现堆积的情况，使用火狐情况较好一些
![image](https://github.com/user-attachments/assets/fbcc5eef-7424-4f60-8879-f59d4a2ae411)
![image](https://github.com/user-attachments/assets/a22c68ca-c1fc-437f-a6a2-f1a5a02a5042)
修改 CSS 样式时发现，设置 .bbc-bangumi-label 的 width: 30% 似乎能适配大部分窗体情况
![image](https://github.com/user-attachments/assets/50e33616-fff2-411c-a463-75843a874141)

**Comment by yixiaojiu** [comment]
非常感谢你提供的详细描述。自定义样式问题我明天看看。响应式问题应该改了，还没有测试发版，我明天测试一下，然后更新一下 valaxy 插件

**Comment by yixiaojiu** [comment]
valaxy 的 addon 已经发版了，辛苦你更新看一下啦😊

**Comment by mewhz** [comment]
非常感谢您的及时更新，已经完美解决问题啦
